### ISSUE TITLE
Exception during any search

### ISSUE THREAD

**Issue by slavniyteo** [LINKIWI/google-terminal-search#2]
Any search returns stack trace.
![image](https://user-images.githubusercontent.com/18638390/28264301-f8e42084-6af2-11e7-8878-7b5736fa5e43.png)

I see last commit was at 2015... But who knows? =)

**Comment by LINKIWI** [comment]
@slavniyteo Hi, sorry for the late response. This was a low-effort project I hacked together in 2015; I'm pretty sure the API endpoint I was using was deprecated a long time ago.

My recommendation is to search for an alternative client, since I have no intentions of further maintaining this repository.
